// Generated by `pnpm <example>:build-dev` from WEBCHAT_DEMO_CLIENT_KEY -- do not edit, not checked in.
window.MAGICSTORE_BUILD = {
  target: "dev",
  apiBaseUrl: "https://api.dev.connectly.ai",
  clientKey: "SKoOimb6xSgq8jqvQ03Rqia5HMqCGfPyljlLLvgIcaKtmKOO4i",
};
