// Generated by `pnpm <example>:build-prod` from DEMO_CLIENT_KEY -- do not edit, not checked in.
window.MAGICSTORE_BUILD = {
  target: "prod",
  apiBaseUrl: "https://api.connectly.ai",
  clientKey: "JaYXuddBMD6f6qzzAgjIPHT4QuXmnA0JQkPIPCtVwFxnbN7try",
};
